### ISSUE TITLE
idle animation

### ISSUE THREAD

**Issue by ashleyundead** [inuNorii/Dark-Souls-III-CT-TGA#14]
hey, can you please update the idle animation that was avaliable in the old cheat table ? which allow us to cancel any animation

**Comment by Gate9350** [comment]
The pointer's base address was updated as necessary by Norii. There's no issue.

**Comment by inuNorii** [comment]
Unless you meant something else, "Idle Animation" should still be working as always.

**Comment by ashleyundead** [comment]
> Unless you meant something else, "Idle Animation" should still be working as always.

in the old table i used to use a hotkey for idle animation and when i press it in game it cancel any animation that im doing , but i can't do it right now with the new table so what should i do ? sorry im a complete beginner lol

**Comment by inuNorii** [comment]
You'll just have to set the hotkey again.
Right-click on "Idle Animation" to get the option for it.

Closing this as it's not an issue with the cheat table.
