### ISSUE TITLE
unlock summoning limit

### ISSUE THREAD

**Issue by dodoglo** [inuNorii/Dark-Souls-III-CT-TGA#15]
when i unlock summoning limit game crashes after a few seconds.  i tried to ask on discord but got banned.
this "unlock summoning limit" online feature is present in your CE, so why if it doesn't work I cant ask how to fix it?

**Comment by dodoglo** [comment]
Your function does not work and you ban for asking how to fix lmao xd funny

**Comment by inuNorii** [comment]
You asked for a feature from a different tool specifically for online cheating, after having already been warned once.
"Unlock summon limit" might just be broken because of the latest game update.
As it's an online feature, I won't be updating it unless someone else does.

**Comment by dodoglo** [comment]
"Trigger Covenant" can be done somehow, via CE, by giving an item of clothing some kind of effect and wearing it. this is not a function from another mod btw

**Comment by inuNorii** [comment]
Anything can be done via CE, it's not a feature in my table though and won't be.

**Comment by dodoglo** [comment]
gg wp point down dung pie 360
